//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "documents")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub task_id: String,
    pub scope: String,
    #[sea_orm(unique_key = "uq_documents_path")]
    pub root_dir: String,
    #[sea_orm(unique_key = "uq_documents_path")]
    pub rel_path: String,
    pub created_at: String,
    pub updated_at: String,
    pub content_digest: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
