#!/usr/bin/env bash
set -euo pipefail

template_root="$(cd "$(dirname "$0")/.." && pwd)"

if [ "$#" -gt 1 ]; then
  echo "usage: generate-module-registry.sh [output-directory]" >&2
  exit 2
fi

# Discovery is the folder tree itself: every modules/<name>/rust crate joins
# the registry, sorted by Module name so composition is deterministic.
module_names=""
for module_directory in "${template_root}"/modules/*/rust; do
  [ -f "${module_directory}/Cargo.toml" ] || continue
  module_names="${module_names}$(basename "$(dirname "${module_directory}")")"$'\n'
done
module_names="$(printf '%s' "${module_names}" | LC_ALL=C sort)"

if [ -z "${module_names}" ]; then
  echo "ERROR: no Module crates found under modules/*/rust." >&2
  exit 1
fi

scratch_directory="$(mktemp -d)"
trap 'rm -rf "${scratch_directory}"' EXIT
generated_directory="${scratch_directory}/module-registry"
mkdir -p "${generated_directory}/src"

{
  cat <<'HEADER'
# @generated by scripts/generate-module-registry.sh from modules/*/rust.
# Regenerate with `npm run generate`; never hand-edit.

[package]
name = "module-registry"
version = "0.1.0"
description = "The generated composition registry linking every Module into the host"
edition = "2021"
publish = false

[lib]
name = "module_registry"

[dependencies]
module-host = { path = "../module-host" }
sea-orm-migration = { workspace = true }
HEADER
  while IFS= read -r module_name; do
    printf '%s-module = { path = "../../modules/%s/rust" }\n' "${module_name}" "${module_name}"
  done <<<"${module_names}"
} >"${generated_directory}/Cargo.toml"

{
  cat <<'HEADER'
//! @generated by scripts/generate-module-registry.sh from modules/*/rust.
//! The composition registry: the one generated link between the discovered
//! Modules and the host. Regenerate with `npm run generate`; never hand-edit.

use sea_orm_migration::prelude::*;

/// Every Module's definition, sorted by Module name.
pub fn modules() -> Vec<module_host::ModuleDef> {
    vec![
HEADER
  while IFS= read -r module_name; do
    printf '        %s_module::module_def(),\n' "$(printf '%s' "${module_name}" | tr '-' '_')"
  done <<<"${module_names}"
  cat <<'FOOTER'
    ]
}

/// One deterministic migration sequence: Modules in name order, each
/// Module's migrations in their declared order.
pub struct Migrator;

#[async_trait::async_trait]
impl MigratorTrait for Migrator {
    fn migrations() -> Vec<Box<dyn MigrationTrait>> {
        modules()
            .into_iter()
            .flat_map(|module| module.migrations())
            .collect()
    }
}

/// The named Module's definition, if that Module is registered.
pub fn module(name: &str) -> Option<module_host::ModuleDef> {
    modules().into_iter().find(|module| module.name() == name)
}
FOOTER
} >"${generated_directory}/src/lib.rs"

# rustfmt settles list wrapping so the emitted source stays byte-stable under
# `cargo fmt --check` no matter how many Modules the vec! literal carries.
rustfmt --edition 2021 "${generated_directory}/src/lib.rs"

if [ "$#" -eq 1 ]; then
  output_directory="$1"
  if [ -e "${output_directory}" ]; then
    echo "ERROR: generation output already exists: ${output_directory}" >&2
    exit 1
  fi
  mkdir -p "$(dirname "${output_directory}")"
  mv "${generated_directory}" "${output_directory}"
  exit 0
fi

# This is the one deliberate replacement boundary: the directory is entirely
# generator-owned and the exact target is fixed inside this repository.
rm -rf "${template_root}/crates/module-registry"
mv "${generated_directory}" "${template_root}/crates/module-registry"
echo "generated crates/module-registry"
