#!/usr/bin/env bash
set -euo pipefail

template_root="$(cd "$(dirname "$0")/.." && pwd)"

if [ "$#" -gt 1 ]; then
  echo "usage: generate-module-index.sh [output-file]" >&2
  exit 2
fi
output_file="${1:-${template_root}/src/generated/modules.ts}"

# Discovery is the folder tree itself: every modules/<name>/ui package joins
# the index, sorted by Module name so composition is deterministic. Package
# names follow the workspace convention @tauri-graphql-template/<name>-module.
module_names=""
for module_directory in "${template_root}"/modules/*/ui; do
  [ -f "${module_directory}/package.json" ] || continue
  module_names="${module_names}$(basename "$(dirname "${module_directory}")")"$'\n'
done
module_names="$(printf '%s' "${module_names}" | LC_ALL=C sort)"

if [ -z "${module_names}" ]; then
  echo "ERROR: no Module ui packages found under modules/*/ui." >&2
  exit 1
fi

scratch_file="$(mktemp)"
trap 'rm -f "${scratch_file}"' EXIT

{
  cat <<'HEADER'
// @generated by scripts/generate-module-index.sh from modules/*/ui.
// The frontend composition index: the one generated link between the
// discovered Modules and the host UI. Regenerate with `npm run generate`;
// never hand-edit.

HEADER
  while IFS= read -r module_name; do
    printf 'import { moduleDef as %s_module } from "@tauri-graphql-template/%s-module";\n' \
      "$(printf '%s' "${module_name}" | tr '-' '_')" "${module_name}"
  done <<<"${module_names}"
  cat <<'MIDDLE'

/** Every Module's ui definition, sorted by Module name. */
export const modules = [
MIDDLE
  while IFS= read -r module_name; do
    printf '  %s_module,\n' "$(printf '%s' "${module_name}" | tr '-' '_')"
  done <<<"${module_names}"
  printf '];\n'
} >"${scratch_file}"

mkdir -p "$(dirname "${output_file}")"
mv "${scratch_file}" "${output_file}"
trap - EXIT
echo "generated ${output_file#"${template_root}"/}"
