//! @generated by scripts/generate-module-registry.sh from modules/*/rust.
//! The composition registry: the one generated link between the discovered
//! Modules and the host. Regenerate with `npm run generate`; never hand-edit.

use sea_orm_migration::prelude::*;

/// Every Module's definition, sorted by Module name.
pub fn modules() -> Vec<module_host::ModuleDef> {
    vec![
        documents_module::module_def(),
        projects_module::module_def(),
        workspaces_module::module_def(),
    ]
}

/// One deterministic migration sequence: Modules in name order, each
/// Module's migrations in their declared order.
pub struct Migrator;

#[async_trait::async_trait]
impl MigratorTrait for Migrator {
    fn migrations() -> Vec<Box<dyn MigrationTrait>> {
        modules()
            .into_iter()
            .flat_map(|module| module.migrations())
            .collect()
    }
}

/// The named Module's definition, if that Module is registered.
pub fn module(name: &str) -> Option<module_host::ModuleDef> {
    modules().into_iter().find(|module| module.name() == name)
}
